/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const JobId = IDL.Nat;
export const UserId = IDL.Principal;
export const Proposal = IDL.Record({
  'jobId' : JobId,
  'coverLetter' : IDL.Text,
  'proposedPrice' : IDL.Nat,
  'freelancer' : UserId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'customer' : UserId,
  'description' : IDL.Text,
  'isOpen' : IDL.Bool,
  'category' : Category,
  'budget' : IDL.Nat,
});
export const AppRole = IDL.Variant({
  'customer' : IDL.Null,
  'freelancer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'resume' : IDL.Opt(ExternalBlob),
  'displayName' : IDL.Text,
  'appRole' : AppRole,
  'hourlyRate' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptProposal' : IDL.Func([JobId, UserId], [Proposal], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'chooseRole' : IDL.Func([IDL.Bool], [], []),
  'createJob' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat, Category], [JobId], []),
  'downloadResume' : IDL.Func([UserId], [IDL.Opt(ExternalBlob)], ['query']),
  'getAllOpenJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobsByCustomer' : IDL.Func([UserId], [IDL.Vec(Job)], ['query']),
  'getMyJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getMyProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getOpenJobsByCategory' : IDL.Func([Category], [IDL.Vec(Job)], ['query']),
  'getProposalsForJob' : IDL.Func([JobId], [IDL.Vec(Proposal)], ['query']),
  'getPublicProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProposal' : IDL.Func([JobId, IDL.Text, IDL.Nat], [], []),
  'updateMyProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const JobId = IDL.Nat;
  const UserId = IDL.Principal;
  const Proposal = IDL.Record({
    'jobId' : JobId,
    'coverLetter' : IDL.Text,
    'proposedPrice' : IDL.Nat,
    'freelancer' : UserId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'customer' : UserId,
    'description' : IDL.Text,
    'isOpen' : IDL.Bool,
    'category' : Category,
    'budget' : IDL.Nat,
  });
  const AppRole = IDL.Variant({
    'customer' : IDL.Null,
    'freelancer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'resume' : IDL.Opt(ExternalBlob),
    'displayName' : IDL.Text,
    'appRole' : AppRole,
    'hourlyRate' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptProposal' : IDL.Func([JobId, UserId], [Proposal], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'chooseRole' : IDL.Func([IDL.Bool], [], []),
    'createJob' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Category],
        [JobId],
        [],
      ),
    'downloadResume' : IDL.Func([UserId], [IDL.Opt(ExternalBlob)], ['query']),
    'getAllOpenJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobsByCustomer' : IDL.Func([UserId], [IDL.Vec(Job)], ['query']),
    'getMyJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getMyProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getOpenJobsByCategory' : IDL.Func([Category], [IDL.Vec(Job)], ['query']),
    'getProposalsForJob' : IDL.Func([JobId], [IDL.Vec(Proposal)], ['query']),
    'getPublicProfile' : IDL.Func([UserId], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProposal' : IDL.Func([JobId, IDL.Text, IDL.Nat], [], []),
    'updateMyProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };