/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppRole = { 'customer' : null } |
  { 'freelancer' : null };
export type Category = string;
export type ExternalBlob = Uint8Array;
export interface Job {
  'id' : JobId,
  'title' : string,
  'customer' : UserId,
  'description' : string,
  'isOpen' : boolean,
  'category' : Category,
  'budget' : bigint,
}
export type JobId = bigint;
export interface Proposal {
  'jobId' : JobId,
  'coverLetter' : string,
  'proposedPrice' : bigint,
  'freelancer' : UserId,
}
export type UserId = Principal;
export interface UserProfile {
  'bio' : string,
  'resume' : [] | [ExternalBlob],
  'displayName' : string,
  'appRole' : AppRole,
  'hourlyRate' : bigint,
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptProposal' : ActorMethod<[JobId, UserId], Proposal>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'chooseRole' : ActorMethod<[boolean], undefined>,
  'createJob' : ActorMethod<[string, string, bigint, Category], JobId>,
  'downloadResume' : ActorMethod<[UserId], [] | [ExternalBlob]>,
  'getAllOpenJobs' : ActorMethod<[], Array<Job>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJobsByCustomer' : ActorMethod<[UserId], Array<Job>>,
  'getMyJobs' : ActorMethod<[], Array<Job>>,
  'getMyProposals' : ActorMethod<[], Array<Proposal>>,
  'getOpenJobsByCategory' : ActorMethod<[Category], Array<Job>>,
  'getProposalsForJob' : ActorMethod<[JobId], Array<Proposal>>,
  'getPublicProfile' : ActorMethod<[UserId], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProposal' : ActorMethod<[JobId, string, bigint], undefined>,
  'updateMyProfile' : ActorMethod<
    [string, string, Array<string>, bigint, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];